import Foundation

// Auto-generated from Square catalog snapshot.
// Snapshot generated: 2026-03-02T21:49:04.277734Z
enum SquareMenuSeed {
    static let generatedAtISO8601 = "2026-03-02T21:49:04.277734Z"
    static let generatedAtDisplay = "2026-03-02 21:49 UTC"

    static let items: [MenuItem] = [
        MenuItem(id: "MP5D6O74KTUHZK4PUTULOBTB", name: "Christian Brothers Brandy", description: "", price: "$9.00", category: "Brandy/Cognac", tags: ["Brandy/Cognac", "Regular", "Spirits"]),
        MenuItem(id: "3ZOP5ERNPHONB3VX5MIJ5D3W", name: "Flying Leap Lavender Brandy", description: "", price: "$8.00", category: "Brandy/Cognac", tags: ["Brandy/Cognac", "Regular", "Spirits"]),
        MenuItem(id: "7QNLFRYXMFYH7AKWSZLEN53H", name: "Flying Leap Orange Brandy", description: "", price: "$9.00", category: "Brandy/Cognac", tags: ["Brandy/Cognac", "Regular", "Spirits"]),
        MenuItem(id: "JISA5VN2WFBUQVH35NXHTXH7", name: "Flying Leap Spiced Brandy", description: "", price: "$9.00", category: "Brandy/Cognac", tags: ["Brandy/Cognac", "Regular", "Spirits"]),
        MenuItem(id: "CFMPLZKVO3EYJUXC5I46WSTG", name: "Cap Fee", description: "", price: "$3.00", category: "Cap and Cork Fees", tags: ["Cap and Cork Fees", "Regular"]),
        MenuItem(id: "LTP5PZMEI5DNUJKFI2G52IHO", name: "Cork Fee", description: "", price: "$7.00", category: "Cap and Cork Fees", tags: ["Cap and Cork Fees", "Regular"]),
        MenuItem(id: "23BX3RN64KKCGDL2Y3MJCBEJ", name: "Amaretto", description: "", price: "$7.50", category: "Cordials", tags: ["Cordials", "Regular"]),
        MenuItem(id: "BMUTJ2ZIZOIIWINMK5U2NFM3", name: "Hemosu Straight Soju", description: "", price: "$7.00", category: "Cordials", tags: ["Cordials", "Regular"]),
        MenuItem(id: "YPLNUHXISMMIA2LKGE5DKO3S", name: "Jagermeister", description: "", price: "$8.00", category: "Cordials", tags: ["Cordials", "Regular"]),
        MenuItem(id: "HJCEDADXL4OITZYVWCVIJPBU", name: "St. George Absinthe", description: "", price: "$10.00", category: "Cordials", tags: ["Cordials", "Regular"]),
        MenuItem(id: "RBNUEVSIKCABVRU7PJTZFKQ5", name: "Vicario Walnut Liqueur", description: "", price: "$8.00", category: "Cordials", tags: ["Cordials", "Regular"]),
        MenuItem(id: "WGCXYDUIA4PZOMXBCFMGPABP", name: "Bodini Malbec", description: "", price: "$9.00", category: "Draft Wine", tags: ["Draft Wine", "Regular"]),
        MenuItem(id: "UQH4DZQN5WMDT6I3LNRNY4W4", name: "Marion Mead", description: "", price: "$11.50", category: "Draft Wine", tags: ["Draft Wine", "Regular"]),
        MenuItem(id: "JED7C7FVJQ5HGJYMNQY27XBV", name: "Blue Clover Gin", description: "", price: "$9.00", category: "Gin", tags: ["Gin", "Regular", "Spirits"]),
        MenuItem(id: "RMNT66AIVOMOW3PYDTF2DGYZ", name: "Hendricks Gin", description: "", price: "$8.50", category: "Gin", tags: ["Gin", "Regular", "Spirits"]),
        MenuItem(id: "XNAVO7AQDZV47V4D5DXAYXAG", name: "St. George Terrior", description: "", price: "$11.00", category: "Gin", tags: ["Gin", "Regular"]),
        MenuItem(id: "VH2FZBV6AQTV3G6IZWAQEVJV", name: "Casa Twist", description: "", price: "$11.00", category: "Mixed Drinks", tags: ["Mixed Drinks", "Regular"]),
        MenuItem(id: "74NABPPGZYKJ5ZZYU34SENQS", name: "Long Island", description: "", price: "$9.00", category: "Mixed Drinks", tags: ["Mixed Drinks", "Regular"]),
        MenuItem(id: "XQBY3ZIXSFKAL36BAZ6EI53I", name: "Employee Red Bull", description: "", price: "$2.50", category: "Non Alch", tags: ["Non Alch", "Regular"]),
        MenuItem(id: "WJJQBGV3WK72GUTEV3BBEIDA", name: "Lagunitas Hop Water Non-Alcoholic BOTTLE", description: "", price: "$3.50", category: "Non Alch", tags: ["Non Alch", "Regular"]),
        MenuItem(id: "LLRCUWUT6CHM2MSSKXTW7FNY", name: "Redbull", description: "", price: "$3.50", category: "Non Alch", tags: ["Non Alch", "Regular"]),
        MenuItem(id: "I7BFHISINF4JUGE3HKEPB6RY", name: "Soft Drink", description: "", price: "$3.00", category: "Non Alch", tags: ["Non Alch", "Regular"]),
        MenuItem(id: "UBVWMHRV3VY4SU772TJ6WINL", name: "Coors Light (BOTTLE)", description: "", price: "$4.50", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "EM7FBD6FL2MAWNLUUVDCZLDM", name: "Dos XX Lager (BOTTLE)", description: "", price: "$4.50", category: "Package", tags: ["Package", "Regular", "Beer"]),
        MenuItem(id: "Z5HIXPLPHKF4OICSBK45NZIX", name: "Michelob Ultra (BOTTLE)", description: "", price: "$4.50", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "RVD47DFEXVOWQP5CPSLXJ3T2", name: "Miller Lite (BOTTLE)", description: "", price: "$4.50", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "TBNH4TDBSPCOH24ZCH5INX7P", name: "Weihenstephaner Hefeweissbier Dunkel", description: "", price: "$5.00", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "7KJNPUXQLIAA52HK6XHEWAS2", name: "White Claw Black Cherry", description: "", price: "$2.00", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "JBGQZWSOKA7Q3YQKAE2GBNQX", name: "White Claw Mango", description: "", price: "$2.00", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "SRXGWICLDC5S3YMW5VUMLXSP", name: "White Claw Ruby Grapefruit", description: "", price: "$2.00", category: "Package", tags: ["Package", "Regular"]),
        MenuItem(id: "YGD64WLYXTKHARR25WPNUV22", name: "Bell's Two Hearted IPA", description: "", price: "$3.00", category: "Package (Finley)", tags: ["Package (Finley)", "Regular", "Beer"]),
        MenuItem(id: "PPOEE7FILT3WZWMSDK5KTYAP", name: "Dragoon Brewing Pilsner (CAN)", description: "", price: "$4.50", category: "Package (Finley)", tags: ["Package (Finley)", "Regular"]),
        MenuItem(id: "UJETSX2TR4UKRDVQF5Y5UUTY", name: "Dragoon IPA (CAN)", description: "", price: "$4.50", category: "Package (Finley)", tags: ["Package (Finley)", "Regular", "Beer"]),
        MenuItem(id: "LZIAMNMUQYLM5RTCUKVMU5XS", name: "Sierra Nevada Hazy Little Thing IPA TALL BOY", description: "", price: "$4.00", category: "Package (Hensley)", tags: ["Package (Hensley)", "Regular", "Beer"]),
        MenuItem(id: "HHTOCFPJWLIZIAP2PAPLVUMV", name: "Del Bac Dorado Mesquite Smoked Whiskey Bottle", description: "", price: "$64.50", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "XAHNA3NS2VP7FLJNY5QGXC2X", name: "Don Pilar Tequila Blanco", description: "", price: "$39.75", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "FB4MHHOHCL3WO7C33ZTQHLAP", name: "E.H. Taylor Single Barrel Bourbon Whiskey Bottle", description: "", price: "$150.00", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "TEY6PHR23HDD5THFQRBJSK5N", name: "E.H. Taylor Small Batch Bottle", description: "", price: "$69.99", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular"]),
        MenuItem(id: "DICVWIMJGRMKITRJK7DBU5MW", name: "E.H. Taylor Small Batch Bourbon Bottle", description: "", price: "$69.99", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "3EO2OGN6J6NCCLOEU4OMHA6M", name: "Eagle Rare Bourbon Bottle", description: "", price: "$69.99", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "JPCNXAW5CSOSORX7NMRM7TV5", name: "Four Roses Bourbon Bottle", description: "", price: "$21.50", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits", "Wine"]),
        MenuItem(id: "PAV6M6JIIQCR7Y7MCZHC676V", name: "Stagg Jr. Bourbon Bottle", description: "", price: "$89.00", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "OEGIXMPVXHB2LP6RXIXPMWC4", name: "Whistlepig 10 Year Rye Whiskey Bottle", description: "", price: "$80.00", category: "Packaged Spirits", tags: ["Packaged Spirits", "Regular", "Spirits"]),
        MenuItem(id: "ZMI63ZX6URB7KKH4OCLEHBTE", name: "Bacardi Silver Rum", description: "", price: "$10.50", category: "Rum", tags: ["Rum", "Regular", "Spirits"]),
        MenuItem(id: "GFARZRHUS3WGO2GJ764QMXZF", name: "Bumbu Rum", description: "", price: "$11.50", category: "Rum", tags: ["Rum", "Regular", "Spirits"]),
        MenuItem(id: "IDHIOD2A4JKFCS46PBDH2LPB", name: "Arette Reposado", description: "", price: "$10.00", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular"]),
        MenuItem(id: "4YGEGA6MZDU4C7DYRV3UZSQH", name: "Artenom 1146 Anejo", description: "", price: "$16.00", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular"]),
        MenuItem(id: "LVLEJJAQTSI2DKWPFSUYTQHV", name: "Corazon Silver", description: "", price: "$10.50", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular"]),
        MenuItem(id: "AZSYF2PME5GXPYIZAL2SF7YS", name: "Dobel Maestro Añejo", description: "", price: "$13.00", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular"]),
        MenuItem(id: "WFCQDYMN3R72JLNVKVKK7TBS", name: "Dobel Maestro Diamante", description: "", price: "$16.50", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular"]),
        MenuItem(id: "ARXBWIMDPEAA37XO3H5XBPMI", name: "Tequila Ocho Añejo", description: "", price: "$12.00", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular", "Spirits"]),
        MenuItem(id: "M5QIVLMWZETRPOGC6FPLJR6F", name: "Tequila Ocho Reposado", description: "", price: "$10.00", category: "Tequila/Mezcal", tags: ["Tequila/Mezcal", "Regular", "Spirits"]),
        MenuItem(id: "BLED2OILPXZYUMCUZV2HD5K4", name: "Stoli Cucumber Vodka", description: "", price: "$8.00", category: "Vodka", tags: ["Vodka", "Regular", "Spirits"]),
        MenuItem(id: "3SPHNWUJ52FNQHYN7523HXV5", name: "Titos Vodka", description: "", price: "$9.50", category: "Vodka", tags: ["Vodka", "Regular", "Spirits"]),
        MenuItem(id: "4JHLQT2BVN6PPKSM466P4CNC", name: "Aberfeldy 12 Year Scotch", description: "", price: "$12.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "LBBT4S75VR3ZRISKLRJXUTJQ", name: "Amrut Fusion Whiskey", description: "", price: "$14.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "72G4GV7SQKCN2BWBIEEI4FDX", name: "Blantons Bourbon", description: "", price: "$19.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "JILSCTISQLEIDSGLMMLQPB7N", name: "Buffalo Trace Bourbon", description: "", price: "$11.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "QIDMPFTDENQ6DQFMFZVHB2LX", name: "Bushmills Red Bush Irish Whiskey", description: "", price: "$9.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "CC36DOSR2XTGXS2OXZX7SL53", name: "Clan Macgregor Scotch", description: "", price: "$8.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "P7EI4GYIDEZBDNRBVS4EK2QI", name: "Del Bac Classic Whiskey", description: "", price: "$11.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "OAUGY5X2PLS2DWBCQS4LVS74", name: "Del Bac Dorado Mesquite Smoked Whiskey", description: "", price: "$12.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "MC5T3FBPWK5MEIA32CSDOCJI", name: "E.H. Taylor Single Proof Bourbon", description: "", price: "$16.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "YGCVHF4GMGQ67AGOPR4WXPK7", name: "E.H. Taylor Small Batch Bourbon", description: "", price: "$12.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "LQBHJA4QOIFHC4BEC2Z3HO2W", name: "Fireball Cinnamon Whiskey", description: "", price: "$8.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "RKCOYNIZKYQXIY3SRRD3PDL2", name: "Flying Leap Bourbon", description: "", price: "$12.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "RKTSRPGEBDZ2HX2QWJZRQK6C", name: "Flying Leap Rye Whiskey", description: "", price: "$10.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "R2R5KPIUCVGBHQDX2ZAUAVFA", name: "Four Roses Bourbon", description: "", price: "$8.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits", "Wine"]),
        MenuItem(id: "45UVRBKDMPO7DTNEQRQCCEQ3", name: "Four Roses Limited Edition 2020 Small Batch Strength", description: "", price: "$32.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Wine"]),
        MenuItem(id: "6JWX4XVOXSBXMTGPT6AUORHP", name: "George T. Stagg Barrel Proof Bourbon", description: "", price: "$25.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "O45LM22JBT2YBVB7OZ5NTSM5", name: "Glenfiddich 12 Year Scotch", description: "", price: "$11.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "ZOBAWHWQB2QYIGM3PY75WKZP", name: "Glenfiddich 14 Year Scotch", description: "", price: "$15.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "FCVVZEUFWUSYOW4AILRSVVEW", name: "Glenlivet 12 Year Scotch", description: "", price: "$12.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "Z37LJIQL57VNZH63L6EUCTJ6", name: "Glenlivet 15 Year Scotch", description: "", price: "$17.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "H24VJ7K2OCTXDDIKBJ33D7W5", name: "Glenlivet Caribbean Reserve Scotch", description: "", price: "$11.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "RGUCRVDHOGBJ4NAWCEUIVYPD", name: "Glenlivet Founders Reserve Scotch", description: "", price: "$11.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "T22A52FSYXRFGSOY2NFGFXV5", name: "Harelston Green Blended Scotch", description: "", price: "$9.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "52XKDLBRT7OFTQTQIXRSOD5B", name: "Highland Park 12 Year Scotch", description: "", price: "$11.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "AAX37FQ5MF6OG5M2UJCTCA45", name: "Jack Daniels Whiskey", description: "", price: "$8.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "PZ3URMKEVCCZXCZDDME5XZXP", name: "Jim Beam Bourbon", description: "", price: "$8.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "WDH37QPP3IGWWEN36GMJZC37", name: "McByirden Speyside Single Malt Scotch", description: "", price: "$8.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "QLK7LTZVDE4JIXNAQLVLUC46", name: "Old Rip Van Winkle 10 Year Bourbon", description: "", price: "$35.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "JXWRKUHZDBKQ5AGCUQBJJ3ID", name: "Pendleton Canadian Whiskey", description: "", price: "$8.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "IFDXI7AB4VPOLVDI3WQTODQT", name: "Ram’s Point", description: "", price: "$8.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular"]),
        MenuItem(id: "F2I6Y2ZBP36OTOZUGOJIY2XQ", name: "Sacred Stave Single Malt Whiskey", description: "", price: "$10.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "MAULNRWKAVHLRRQNZHSLJQJN", name: "Sazerac Rye Whiskey", description: "", price: "$9.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "4QJ4BP7335HWC3V5M37LCCC3", name: "Southern Comfort", description: "", price: "$8.50", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular"]),
        MenuItem(id: "34RHBCB4WEMFNCQOPVGKPA7G", name: "St. George Baller Single Malt Whiskey", description: "", price: "$12.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "VMLR5P3TVLA72HQPQON6YML3", name: "Stagg Bourbon", description: "", price: "$14.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "7XHK2BIKFVXMUFIDT6INGOSN", name: "Templeton Rye 4 Year Whiskey", description: "", price: "$9.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "SLVUDMRD6CUKLYFH76AQOXN3", name: "Thomas H. Handy Sazerac Rye Whiskey", description: "", price: "$33.99", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "FM7TR5WNVPL2VXARZ3NN5FFA", name: "Thomas S. Moore Cabernet Sauvignon Whiskey", description: "", price: "$14.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits", "Wine"]),
        MenuItem(id: "KQRNIRDLWXNI7YMXHJZC2DX7", name: "Thomas S. Moore Chardonnay Whiskey", description: "", price: "$15.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits", "Wine"]),
        MenuItem(id: "MXR4VYPXRGOGD45OKBCZD64S", name: "Thomas S. Moore Port Casks Whiskey", description: "", price: "$13.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "56VE6LICBAH4JGDSUV5UHL6N", name: "Van Winkle Special Reserve 12 Year Bourbon", description: "", price: "$40.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "UIDGCXGJA5EIT6SNIC264ZDG", name: "Weller 12 Bourbon", description: "", price: "$18.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "EDAVT6UNBHKQBJACJ4YN6K3O", name: "Whistlepig Farmstock Rye Whiskey", description: "", price: "$25.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "WCKA4TOM2MASONUYDR3ZW3EV", name: "Whistlepig Homestock Whiskey Blend", description: "", price: "$20.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "PNN4G77KITJEBH32NDGGFGNR", name: "Whistlepig Piggyback 6 Year Rye Whiskey", description: "", price: "$11.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
        MenuItem(id: "NKBJOQP62XL32BUX2ROIVGE3", name: "Wild Turkey Longbranch Bourbon", description: "", price: "$8.00", category: "Whiskey/Scotch", tags: ["Whiskey/Scotch", "Regular", "Spirits"]),
    ]
}
